# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  major: 0
  minor: 1
  patch: 0
  buildConfiguration: 'Release'
  pre: $(Date:yyyyMMdd)$(Rev:.rrr)-$(Build.SourceBranchName)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Run build'
- script: dotnet test ./tests/Occurrence.Tests --configuration $(buildConfiguration) --logger trx
  displayName: 'Run tests'
- script: dotnet pack ./src/Occurrence --configuration $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch)-$(pre)
  displayName: 'Package'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'